name: Run Shell Scripts Based on PR Label

on:
  push:
    branches:
      - main

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

  determine-script:
    runs-on: ubuntu-latest
    needs: checkout
    outputs:
      script-file: ${{ steps.script.outputs.script-file }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Determine script to run
        id: script
        shell: bash
        run: |
          labels=${{ toJson(github.event.pull_request.labels.*.name) | jq -r '.[].name' }}
          echo $labels
          if [[ "$labels" == *"migrate_restart"* ]]; then
            echo "migrate_and_restart" >> $GITHUB_OUTPUT
          elif [[ "$labels" == *"migrate"* ]]; then
            echo "migrate" >> $GITHUB_OUTPUT
          elif [[ "$labels" == *"restart"* ]]; then
            echo "restart." >> $GITHUB_OUTPUT
          else
            echo "migrate_and_restart" >> $GITHUB_OUTPUT
            exit 1
